- https://github.com/gotgenes/2014-05-29-ucsd
- https://github.com/badger-d/2014-06-02-monash
- https://github.com/apawlik/2014-06-03-cern
- https://github.com/gdevenyi/2014-06-04-cornell
- https://github.com/luispedro/2014-06-10-cyi
- https://github.com/wltrimbl/2014-06-10-spelman
- https://github.com/luispedro/2014-06-15-khbp
- https://github.com/BernhardKonrad/2014-06-16-davis
- https://github.com/ptone/2014-06-16-claremont
- https://github.com/swcarpentry/2014-06-16-toronto
- https://github.com/cliburn/2014-06-16-duke
- https://github.com/cavestruz/2014-06-20-yale
- https://github.com/dhavide/2014-06-22-caims
- https://github.com/cavestruz/2014-06-24-ru
- https://github.com/swcarpentry/2014-06-24-wise-penn
- https://github.com/DevasenaInupakutika/2014-06-25-Reading
- https://github.com/jrherr/2014-06-26-nd
- https://github.com/ivanov/2014-06-30-stanford
- https://github.com/dhavide/2014-07-02-smu
- https://github.com/cmacdonell/2014-07-10-epl
- https://github.com/swcarpentry/2014-07-08-wise-toronto
- https://github.com/guyrt/2014-07-08-stonybrook
- https://github.com/jrherr/2014-07-10-esip
- https://github.com/swcarpentry/2014-07-15-toronto
- https://github.com/swcarpentry/2014-07-17-aspb
- https://github.com/hpcarcher/2014-07-21-cranfield
- https://github.com/philippbayer/2014-07-30-pyconaus
- https://github.com/vu-bc/2014-08-12-vu
- https://github.com/mollygibson/2014-08-11-wustl
- https://github.com/resbaz/2014-08-18-unimelb
- https://github.com/jrherr/2014-09-11-udel
- https://github.com/resbaz/2014-09-15-unimelb
